//! File: domain/ui/ui_controls/src/validation.rs
//! Crate: ui_controls

use std::collections::{BTreeMap, BTreeSet};

use serde::{Deserialize, Serialize};
use ui_schema::{UiSchema, UiSchemaRef, UiSchemaShape};

use crate::diagnostics::ControlDiagnosticId;
use crate::ids::{ControlKindId, ControlPackageId};
use crate::kernel::{ControlKernelDescriptor, ControlKernelKind};
use crate::metadata::ControlMountEligibility;
use crate::package::{ControlKindDescriptor, ControlModuleDescriptor, ControlPackageDescriptor};
use crate::schema::ControlSchemaDescriptor;

#[derive(Clone, Debug, PartialEq, Eq, Serialize, Deserialize)]
pub struct ControlPackageValidationReport { pub diagnostics: Vec<ControlPackageValidationDiagnostic> }
impl ControlPackageValidationReport { pub fn new() -> Self { Self { diagnostics: Vec::new() } } pub fn is_valid(&self) -> bool { !self.diagnostics.iter().any(|diagnostic| diagnostic.severity == ControlPackageValidationSeverity::Error) } pub fn push(&mut self, diagnostic: ControlPackageValidationDiagnostic) { self.diagnostics.push(diagnostic); } pub fn extend(&mut self, report: ControlPackageValidationReport) { self.diagnostics.extend(report.diagnostics); } pub fn has_reason(&self, reason: ControlPackageValidationReason) -> bool { self.diagnostics.iter().any(|diagnostic| diagnostic.reason == reason) } }
impl Default for ControlPackageValidationReport { fn default() -> Self { Self::new() } }

#[derive(Clone, Debug, PartialEq, Eq, Serialize, Deserialize)]
pub struct ControlPackageValidationDiagnostic { pub diagnostic_id: ControlDiagnosticId, pub severity: ControlPackageValidationSeverity, pub scope: ControlPackageValidationScope, pub path: ControlPackageValidationPath, pub reason: ControlPackageValidationReason, pub message: String }
impl ControlPackageValidationDiagnostic { pub fn package(package_id: ControlPackageId, reason: ControlPackageValidationReason, message: impl Into<String>) -> Self { Self::new(ControlPackageValidationScope::Package { package_id }, ControlPackageValidationPath::new("package"), reason, message) } pub fn kind(control_kind_id: ControlKindId, reason: ControlPackageValidationReason, message: impl Into<String>) -> Self { Self::new(ControlPackageValidationScope::Kind { control_kind_id }, ControlPackageValidationPath::new("control_kind"), reason, message) } pub fn new(scope: ControlPackageValidationScope, path: ControlPackageValidationPath, reason: ControlPackageValidationReason, message: impl Into<String>) -> Self { Self { diagnostic_id: ControlDiagnosticId::new(format!("runenwerk.ui.controls.validation.{}", reason.as_snake_case())), severity: ControlPackageValidationSeverity::Error, scope, path, reason, message: message.into() } } }

#[derive(Clone, Copy, Debug, PartialEq, Eq, Serialize, Deserialize)]
pub enum ControlPackageValidationSeverity { Info, Warning, Error }

#[derive(Clone, Debug, PartialEq, Eq, Serialize, Deserialize)]
pub enum ControlPackageValidationScope { Package { package_id: ControlPackageId }, Kind { control_kind_id: ControlKindId } }

#[derive(Clone, Debug, PartialEq, Eq, Serialize, Deserialize)]
pub struct ControlPackageValidationPath { pub segments: Vec<String> }
impl ControlPackageValidationPath { pub fn new(segment: impl Into<String>) -> Self { Self { segments: vec![segment.into()] } } }

#[derive(Clone, Copy, Debug, PartialEq, Eq, Serialize, Deserialize)]
pub enum ControlPackageValidationReason { MissingPackageMetadata, MissingKindMetadata, MissingSchema, MissingKernel, MissingFixture, MissingDiagnostic, MissingMigration, MissingStory, MissingRoute, MissingCapability, MissingTargetProfile, MissingMountEvidence, DuplicatePackageId, DuplicateControlKindId, DuplicateSchemaRef, DuplicateKernelId, DuplicateFixtureId, DuplicateDiagnosticId, DuplicateMigrationId, DuplicateStoryId, DuplicateRouteRequirement, InvalidDeprecation, InvalidMigrationVersion, InvalidMountEligibility, UnsupportedTargetProfile, UnresolvedReference, RenderEvidenceMissing, BudgetEvidenceMissing }
impl ControlPackageValidationReason { pub const fn as_snake_case(self) -> &'static str { match self { Self::MissingPackageMetadata => "missing_package_metadata", Self::MissingKindMetadata => "missing_kind_metadata", Self::MissingSchema => "missing_schema", Self::MissingKernel => "missing_kernel", Self::MissingFixture => "missing_fixture", Self::MissingDiagnostic => "missing_diagnostic", Self::MissingMigration => "missing_migration", Self::MissingStory => "missing_story", Self::MissingRoute => "missing_route", Self::MissingCapability => "missing_capability", Self::MissingTargetProfile => "missing_target_profile", Self::MissingMountEvidence => "missing_mount_evidence", Self::DuplicatePackageId => "duplicate_package_id", Self::DuplicateControlKindId => "duplicate_control_kind_id", Self::DuplicateSchemaRef => "duplicate_schema_ref", Self::DuplicateKernelId => "duplicate_kernel_id", Self::DuplicateFixtureId => "duplicate_fixture_id", Self::DuplicateDiagnosticId => "duplicate_diagnostic_id", Self::DuplicateMigrationId => "duplicate_migration_id", Self::DuplicateStoryId => "duplicate_story_id", Self::DuplicateRouteRequirement => "duplicate_route_requirement", Self::InvalidDeprecation => "invalid_deprecation", Self::InvalidMigrationVersion => "invalid_migration_version", Self::InvalidMountEligibility => "invalid_mount_eligibility", Self::UnsupportedTargetProfile => "unsupported_target_profile", Self::UnresolvedReference => "unresolved_reference", Self::RenderEvidenceMissing => "render_evidence_missing", Self::BudgetEvidenceMissing => "budget_evidence_missing" } } }

impl ControlKindDescriptor { pub fn validate_contract(&self) -> ControlPackageValidationReport { let mut report = ControlPackageValidationReport::new(); if self.display_name.trim().is_empty() { report.push(ControlPackageValidationDiagnostic::kind(self.control_kind_id.clone(), ControlPackageValidationReason::MissingKindMetadata, "control kind display name must not be empty")); } if self.description.trim().is_empty() { report.push(ControlPackageValidationDiagnostic::kind(self.control_kind_id.clone(), ControlPackageValidationReason::MissingKindMetadata, "control kind description must not be empty")); } if self.target_profiles.is_empty() { report.push(ControlPackageValidationDiagnostic::kind(self.control_kind_id.clone(), ControlPackageValidationReason::MissingTargetProfile, "control kind must name at least one target profile")); } if self.diagnostic_ids.is_empty() { report.push(ControlPackageValidationDiagnostic::kind(self.control_kind_id.clone(), ControlPackageValidationReason::MissingDiagnostic, "control kind must name at least one diagnostic")); } if self.fixture_ids.is_empty() { report.push(ControlPackageValidationDiagnostic::kind(self.control_kind_id.clone(), ControlPackageValidationReason::MissingFixture, "control kind must name at least one fixture")); } if self.route_requirements.is_empty() { report.push(ControlPackageValidationDiagnostic::kind(self.control_kind_id.clone(), ControlPackageValidationReason::MissingRoute, "control kind must name at least one route requirement")); } push_duplicate_kind_values(&mut report, &self.control_kind_id, "target_profile", self.target_profiles.iter().map(|profile| profile.as_str().to_owned()), ControlPackageValidationReason::UnsupportedTargetProfile); push_duplicate_kind_values(&mut report, &self.control_kind_id, "route", self.route_requirements.iter().map(|route| route.route_id.as_str().to_owned()), ControlPackageValidationReason::DuplicateRouteRequirement); push_duplicate_kind_values(&mut report, &self.control_kind_id, "story", self.story_ids.iter().map(|story| story.as_str().to_owned()), ControlPackageValidationReason::DuplicateStoryId); if let ControlMountEligibility::RequiresEvidence { story_ids, render_evidence_ids, budget_evidence_ids } = &self.mount_eligibility { if story_ids.is_empty() { report.push(ControlPackageValidationDiagnostic::kind(self.control_kind_id.clone(), ControlPackageValidationReason::MissingMountEvidence, "mount eligibility requires at least one story")); } if render_evidence_ids.is_empty() { report.push(ControlPackageValidationDiagnostic::kind(self.control_kind_id.clone(), ControlPackageValidationReason::RenderEvidenceMissing, "mount eligibility requires render evidence")); } if budget_evidence_ids.is_empty() { report.push(ControlPackageValidationDiagnostic::kind(self.control_kind_id.clone(), ControlPackageValidationReason::BudgetEvidenceMissing, "mount eligibility requires budget evidence")); } } report } }
