[package]
name = "runenwerk_arena"
version = "0.1.0"
edition = "2024"
publish = false
license.workspace = true

[dependencies]
engine = { path = "../../engine" }
physics.workspace = true
runen-input.workspace = true
runen-spatial.workspace = true
runen_ecs.workspace = true
world_sdf.workspace = true

[dev-dependencies]
product.workspace = true
world_ops.workspace = true
winit = "0.30.9"
