//! WGSL preview entrypoint generation.

use material_graph::MaterialIr;

use super::super::bindings::material_resource_declarations;
use super::super::identity::{fixture_id, output_target_label};
use super::super::{MATERIAL_WGSL_COMPILER_CONTRACT_VERSION, MaterialPreviewFixture};
use super::WgslMaterialProgram;

pub(crate) fn material_program_wgsl(
    ir: &MaterialIr,
    fixture: MaterialPreviewFixture,
    program: &WgslMaterialProgram,
) -> String {
    let generated_lines = if program.lines.is_empty() {
        String::new()
    } else {
        let mut lines = program.lines.join("\n");
        lines.push('\n');
        lines
    };
    let resource_declarations = material_resource_declarations(&program.resource_bindings);
    let output = &program.output;
    format!(
        r#"// generated by runenwerk material compiler v{MATERIAL_WGSL_COMPILER_CONTRACT_VERSION}
// document: {document_id}
// output_target: {output_target}
// fixture: {fixture}

struct VsOut {{
    @builtin(position) clip_position : vec4<f32>,
    @location(0) uv : vec2<f32>,
}};

struct MaterialEvalContext {{
    position : vec3<f32>,
    normal : vec3<f32>,
    distance : f32,
    material_channel : f32,
    density : f32,
    support : f32,
    wetness : f32,
}};

struct MaterialEvalOutput {{
    base_color : vec4<f32>,
    roughness : f32,
    metallic : f32,
    normal_strength : f32,
    emissive : vec3<f32>,
    opacity : f32,
    material_channel : f32,
}};

{resource_declarations}
@vertex
fn vs_main(@builtin(vertex_index) vertex_index: u32) -> VsOut {{
    let pos = array<vec2<f32>, 3>(
        vec2<f32>(-1.0, -3.0),
        vec2<f32>(-1.0, 1.0),
        vec2<f32>(3.0, 1.0),
    );
    var out: VsOut;
    out.clip_position = vec4<f32>(pos[vertex_index], 0.0, 1.0);
    out.uv = pos[vertex_index] * 0.5 + vec2<f32>(0.5, 0.5);
    return out;
}}

fn rw_hash31(value: f32) -> f32 {{
    return fract(sin(value) * 43758.5453123);
}}

fn rw_noise3(position: vec3<f32>) -> f32 {{
    let seed = dot(position, vec3<f32>(12.9898, 78.233, 37.719));
    return rw_hash31(seed);
}}

fn rw_fbm3(position: vec3<f32>) -> f32 {{
    var value = 0.0;
    var amplitude = 0.5;
    var frequency = 1.0;
    for (var octave = 0u; octave < 4u; octave = octave + 1u) {{
        value = value + rw_noise3(position * frequency) * amplitude;
        frequency = frequency * 2.03;
        amplitude = amplitude * 0.5;
    }}
    return clamp(value, 0.0, 1.0);
}}

fn rw_triplanar_weights(normal: vec3<f32>) -> vec3<f32> {{
    let weights = pow(abs(normal), vec3<f32>(4.0));
    let total = max(weights.x + weights.y + weights.z, 0.000001);
    return weights / total;
}}

fn evaluate_material(ctx: MaterialEvalContext) -> MaterialEvalOutput {{
{generated_lines}    var out: MaterialEvalOutput;
    out.base_color = {base_color};
    out.roughness = clamp({roughness}, 0.0, 1.0);
    out.metallic = clamp({metallic}, 0.0, 1.0);
    out.normal_strength = max({normal_strength}, 0.0);
    out.emissive = {emissive};
    out.opacity = clamp({opacity}, 0.0, 1.0);
    out.material_channel = {material_channel};
    return out;
}}

fn fixture_context(uv: vec2<f32>) -> MaterialEvalContext {{
    let centered = uv - vec2<f32>(0.5, 0.5);
    let distance = length(centered) - 0.38;
    var normal = normalize(vec3<f32>(centered, 0.58));
    var density = smoothstep(0.48, 0.18, length(centered));
    var support = 1.0;
    if {fixture_id}u == 1u {{
        density = step(abs(centered.x), 0.36) * step(abs(centered.y), 0.28);
        normal = normalize(vec3<f32>(sign(centered.x) * 0.35, sign(centered.y) * 0.35, 0.75));
    }}
    if {fixture_id}u == 2u {{
        density = smoothstep(0.04, 0.0, abs(centered.y + 0.18));
        normal = vec3<f32>(0.0, 1.0, 0.0);
    }}
    if {fixture_id}u == 3u {{
        support = max(density, step(abs(centered.x), 0.32) * step(abs(centered.y), 0.32));
    }}
    if {fixture_id}u == 4u {{
        density = 0.5 + 0.5 * sin((uv.x + uv.y) * 32.0);
        support = density;
    }}
    return MaterialEvalContext(
        vec3<f32>(centered, density),
        normal,
        distance,
        f32({fixture_id}u),
        density,
        support,
        clamp(uv.y, 0.0, 1.0),
    );
}}

@fragment
fn fs_main(in: VsOut) -> @location(0) vec4<f32> {{
    let ctx = fixture_context(in.uv);
    let material = evaluate_material(ctx);
    let light_dir = normalize(vec3<f32>(0.35, 0.75, 0.55));
    let ndotl = max(dot(ctx.normal, light_dir), 0.12);
    let roughness_lift = mix(0.2, 0.55, material.roughness);
    let metal_tint = mix(material.base_color.rgb, vec3<f32>(0.95, 0.92, 0.85), material.metallic * 0.35);
    let shaded = metal_tint * (ndotl + roughness_lift) + material.emissive;
    return vec4<f32>(clamp(shaded, vec3<f32>(0.0), vec3<f32>(1.0)), material.opacity);
}}
"#,
        document_id = ir.document_id.raw(),
        output_target = output_target_label(ir.output_target),
        fixture = fixture.label(),
        fixture_id = fixture_id(fixture),
        resource_declarations = resource_declarations,
        base_color = output.base_color,
        roughness = output.roughness,
        metallic = output.metallic,
        normal_strength = output.normal_strength,
        emissive = output.emissive,
        opacity = output.opacity,
        material_channel = output.material_channel,
    )
}
