//! WGSL scene-product entrypoint generation.

use material_graph::MaterialIr;

use super::super::MATERIAL_WGSL_COMPILER_CONTRACT_VERSION;
use super::super::bindings::material_resource_declarations;
use super::super::identity::output_target_label;
use super::WgslMaterialProgram;

pub(crate) struct SceneMaterialTableProgramSlot<'a> {
    pub(crate) slot_index: u32,
    pub(crate) material_instance_id: String,
    pub(crate) ir: &'a MaterialIr,
    pub(crate) program: WgslMaterialProgram,
}

pub(crate) fn material_scene_product_wgsl(
    ir: &MaterialIr,
    program: &WgslMaterialProgram,
) -> String {
    let generated_lines = if program.lines.is_empty() {
        String::new()
    } else {
        let mut lines = program.lines.join("\n");
        lines.push('\n');
        lines
    };
    let resource_declarations = material_resource_declarations(&program.resource_bindings);
    let output = &program.output;
    format!(
        r#"// generated by runenwerk material compiler v{MATERIAL_WGSL_COMPILER_CONTRACT_VERSION}
// scene entrypoint generated from material document: {document_id}
// output_target: {output_target}

struct EditorViewportSceneProductUniform {{
    surface : vec4<f32>,
    viewport : vec4<f32>,
    camera_position : vec4<f32>,
    camera_forward : vec4<f32>,
    camera_right : vec4<f32>,
    camera_up : vec4<f32>,
    object_transform : vec4<f32>,
    primitive_params_a : vec4<f32>,
    primitive_params_b : vec4<f32>,
    primitive_flags : vec4<u32>,
    primitive_slot_transforms : array<vec4<f32>, 64>,
    primitive_slot_params_a : array<vec4<f32>, 64>,
    primitive_slot_params_b : array<vec4<f32>, 64>,
    primitive_slot_flags : array<vec4<u32>, 64>,
}};

const MAX_PRIMITIVES : u32 = 64u;

@group(0) @binding(0)
var<uniform> u : EditorViewportSceneProductUniform;

struct VsOut {{
    @builtin(position) clip_position : vec4<f32>,
}};

struct MaterialEvalContext {{
    position : vec3<f32>,
    normal : vec3<f32>,
    distance : f32,
    material_channel : f32,
    density : f32,
    support : f32,
    wetness : f32,
}};

struct MaterialEvalOutput {{
    base_color : vec4<f32>,
    roughness : f32,
    metallic : f32,
    normal_strength : f32,
    emissive : vec3<f32>,
    opacity : f32,
    material_channel : f32,
}};

{resource_declarations}
@vertex
fn vs_main(@builtin(vertex_index) vertex_index: u32) -> VsOut {{
    let pos = array<vec2<f32>, 3>(
        vec2<f32>(-1.0, -3.0),
        vec2<f32>(-1.0, 1.0),
        vec2<f32>(3.0, 1.0),
    );
    var out: VsOut;
    out.clip_position = vec4<f32>(pos[vertex_index], 0.0, 1.0);
    return out;
}}

fn rw_hash31(value: f32) -> f32 {{
    return fract(sin(value) * 43758.5453123);
}}

fn rw_noise3(position: vec3<f32>) -> f32 {{
    let seed = dot(position, vec3<f32>(12.9898, 78.233, 37.719));
    return rw_hash31(seed);
}}

fn rw_fbm3(position: vec3<f32>) -> f32 {{
    var value = 0.0;
    var amplitude = 0.5;
    var frequency = 1.0;
    for (var octave = 0u; octave < 4u; octave = octave + 1u) {{
        value = value + rw_noise3(position * frequency) * amplitude;
        frequency = frequency * 2.03;
        amplitude = amplitude * 0.5;
    }}
    return clamp(value, 0.0, 1.0);
}}

fn rw_triplanar_weights(normal: vec3<f32>) -> vec3<f32> {{
    let weights = pow(abs(normal), vec3<f32>(4.0));
    let total = max(weights.x + weights.y + weights.z, 0.000001);
    return weights / total;
}}

fn evaluate_material(ctx: MaterialEvalContext) -> MaterialEvalOutput {{
{generated_lines}    var out: MaterialEvalOutput;
    out.base_color = {base_color};
    out.roughness = clamp({roughness}, 0.0, 1.0);
    out.metallic = clamp({metallic}, 0.0, 1.0);
    out.normal_strength = max({normal_strength}, 0.0);
    out.emissive = {emissive};
    out.opacity = clamp({opacity}, 0.0, 1.0);
    out.material_channel = {material_channel};
    return out;
}}

const MATERIAL_TABLE_SLOT_CAPACITY : u32 = 64u;

fn material_error_output(material_slot_index: u32) -> MaterialEvalOutput {{
    var out: MaterialEvalOutput;
    out.base_color = vec4<f32>(1.0, 0.0, 0.85, 1.0);
    out.roughness = 1.0;
    out.metallic = 0.0;
    out.normal_strength = 1.0;
    out.emissive = vec3<f32>(0.35, 0.0, 0.25);
    out.opacity = 1.0;
    out.material_channel = f32(material_slot_index);
    return out;
}}

fn evaluate_scene_material(material_slot_index: u32, ctx: MaterialEvalContext) -> MaterialEvalOutput {{
    if material_slot_index >= MATERIAL_TABLE_SLOT_CAPACITY {{
        return material_error_output(material_slot_index);
    }}
    var slot_ctx = ctx;
    slot_ctx.material_channel = f32(material_slot_index);
    return evaluate_material(slot_ctx);
}}

fn sdf_box(sample_pos: vec3<f32>, center: vec3<f32>, half_extents: vec3<f32>) -> f32 {{
    let q = abs(sample_pos - center) - half_extents;
    let outside = length(max(q, vec3<f32>(0.0, 0.0, 0.0)));
    let inside = min(max(q.x, max(q.y, q.z)), 0.0);
    return outside + inside;
}}

fn sdf_sphere(sample_pos: vec3<f32>, center: vec3<f32>, radius: f32) -> f32 {{
    return length(sample_pos - center) - radius;
}}

fn sdf_capsule(sample_pos: vec3<f32>, center: vec3<f32>, radius: f32, half_height: f32) -> f32 {{
    let q = sample_pos - center;
    let clamped_y = clamp(q.y, -half_height, half_height);
    let closest = vec3<f32>(0.0, clamped_y, 0.0);
    return length(q - closest) - radius;
}}

fn sdf_cylinder(sample_pos: vec3<f32>, center: vec3<f32>, radius: f32, half_height: f32) -> f32 {{
    let local = sample_pos - center;
    let d = vec2<f32>(length(local.xz) - radius, abs(local.y) - half_height);
    return min(max(d.x, d.y), 0.0) + length(max(d, vec2<f32>(0.0, 0.0)));
}}

fn sdf_torus(sample_pos: vec3<f32>, center: vec3<f32>, major_radius: f32, minor_radius: f32) -> f32 {{
    let local = sample_pos - center;
    let q = vec2<f32>(length(local.xz) - major_radius, local.y);
    return length(q) - minor_radius;
}}

fn sdf_plane_slab(sample_pos: vec3<f32>, center: vec3<f32>, half_extents: vec3<f32>) -> f32 {{
    let slab_extents = vec3<f32>(max(half_extents.x, 0.05), max(min(half_extents.y, 0.05), 0.01), max(half_extents.z, 0.05));
    return sdf_box(sample_pos, center, slab_extents);
}}

fn primitive_count() -> u32 {{
    return min(u.primitive_flags.y, MAX_PRIMITIVES);
}}

struct SceneDistanceSample {{
    distance : f32,
    sdf_primitive_index : u32,
    material_slot_index : u32,
}};

fn sdf_primitive_slot(sample_pos: vec3<f32>, primitive_index: u32) -> SceneDistanceSample {{
    let slot = u.primitive_slot_flags[primitive_index];
    let center = u.primitive_slot_transforms[primitive_index].xyz;
    let primitive_kind = slot.x;
    let params_a = u.primitive_slot_params_a[primitive_index];
    let params_b = u.primitive_slot_params_b[primitive_index];
    let material_slot_index = slot.w;
    var distance = 0.0;
    if primitive_kind == 1u {{
        distance = sdf_sphere(sample_pos, center, max(params_a.w, 0.05));
        return SceneDistanceSample(distance, primitive_index, material_slot_index);
    }}
    if primitive_kind == 2u {{
        distance = sdf_capsule(sample_pos, center, max(params_b.x, 0.05), max(params_b.y, 0.05));
        return SceneDistanceSample(distance, primitive_index, material_slot_index);
    }}
    if primitive_kind == 3u {{
        distance = sdf_cylinder(sample_pos, center, max(params_b.x, 0.05), max(params_b.y, 0.05));
        return SceneDistanceSample(distance, primitive_index, material_slot_index);
    }}
    if primitive_kind == 4u {{
        distance = sdf_torus(sample_pos, center, max(params_a.w * 1.5, 0.05), max(params_a.w * 0.5, 0.05));
        return SceneDistanceSample(distance, primitive_index, material_slot_index);
    }}
    if primitive_kind == 5u {{
        distance = sdf_plane_slab(sample_pos, center, max(params_a.xyz, vec3<f32>(0.05, 0.05, 0.05)));
        return SceneDistanceSample(distance, primitive_index, material_slot_index);
    }}
    distance = sdf_box(sample_pos, center, max(params_a.xyz, vec3<f32>(0.05, 0.05, 0.05)));
    return SceneDistanceSample(distance, primitive_index, material_slot_index);
}}

fn scene_sdf(sample_pos: vec3<f32>) -> SceneDistanceSample {{
    var best = SceneDistanceSample(1e9, 0u, 0u);
    let count = primitive_count();
    var index = 0u;
    loop {{
        if index >= count {{
            break;
        }}
        let sample = sdf_primitive_slot(sample_pos, index);
        if sample.distance < best.distance {{
            best = sample;
        }}
        index = index + 1u;
    }}
    return best;
}}

fn estimate_normal(sample_pos: vec3<f32>) -> vec3<f32> {{
    let e = 0.001;
    let nx = scene_sdf(sample_pos + vec3<f32>(e, 0.0, 0.0)).distance - scene_sdf(sample_pos - vec3<f32>(e, 0.0, 0.0)).distance;
    let ny = scene_sdf(sample_pos + vec3<f32>(0.0, e, 0.0)).distance - scene_sdf(sample_pos - vec3<f32>(0.0, e, 0.0)).distance;
    let nz = scene_sdf(sample_pos + vec3<f32>(0.0, 0.0, e)).distance - scene_sdf(sample_pos - vec3<f32>(0.0, 0.0, e)).distance;
    return normalize(vec3<f32>(nx, ny, nz));
}}

struct RaymarchResult {{
    hit : bool,
    distance : f32,
    sdf_primitive_index : u32,
    material_slot_index : u32,
}};

fn march_scene(ray_origin: vec3<f32>, ray_dir: vec3<f32>) -> RaymarchResult {{
    var t = 0.0;
    var hit = false;
    var sdf_primitive_index = 0u;
    var material_slot_index = 0u;
    var steps = 0u;
    loop {{
        if steps >= 96u {{
            break;
        }}
        let sample_pos = ray_origin + ray_dir * t;
        let sample = scene_sdf(sample_pos);
        if sample.distance < 0.001 {{
            hit = true;
            sdf_primitive_index = sample.sdf_primitive_index;
            material_slot_index = sample.material_slot_index;
            break;
        }}
        t = t + sample.distance;
        if t > 64.0 {{
            break;
        }}
        steps = steps + 1u;
    }}
    return RaymarchResult(hit, t, sdf_primitive_index, material_slot_index);
}}

fn viewport_background() -> vec4<f32> {{
    return vec4<f32>(0.09, 0.10, 0.12, 1.0);
}}

@fragment
fn fs_main(@builtin(position) position: vec4<f32>) -> @location(0) vec4<f32> {{
    let pixel = position.xy;
    let target_size = max(u.surface.xy, vec2<f32>(1.0, 1.0));
    let viewport_local = pixel / target_size;
    let ndc = vec2<f32>(viewport_local.x * 2.0 - 1.0, 1.0 - viewport_local.y * 2.0);
    if primitive_count() == 0u {{
        return viewport_background();
    }}
    let aspect = target_size.x / target_size.y;
    let tan_half_fov = tan(u.camera_position.w * 0.5);
    let ray_origin = u.camera_position.xyz;
    let ray_dir = normalize(
        u.camera_forward.xyz
        + u.camera_right.xyz * ndc.x * aspect * tan_half_fov
        + u.camera_up.xyz * ndc.y * tan_half_fov
    );
    let march = march_scene(ray_origin, ray_dir);
    if !march.hit {{
        return viewport_background();
    }}
    let sample_pos = ray_origin + ray_dir * march.distance;
    let normal = estimate_normal(sample_pos);
    let material = evaluate_scene_material(march.material_slot_index, MaterialEvalContext(
        sample_pos,
        normal,
        march.distance,
        0.0,
        1.0,
        1.0,
        0.0,
    ));
    let light_dir = normalize(vec3<f32>(0.5, 0.8, 0.35));
    let diff = max(dot(normal, light_dir), 0.1);
    let rim = pow(max(1.0 - max(dot(normal, -ray_dir), 0.0), 0.0), 2.0);
    let lit = material.base_color.rgb * diff + vec3<f32>(0.15, 0.20, 0.28) * rim + material.emissive;
    return vec4<f32>(clamp(lit, vec3<f32>(0.0), vec3<f32>(1.0)), material.opacity);
}}
"#,
        document_id = ir.document_id.raw(),
        output_target = output_target_label(ir.output_target),
        resource_declarations = resource_declarations,
        base_color = output.base_color,
        roughness = output.roughness,
        metallic = output.metallic,
        normal_strength = output.normal_strength,
        emissive = output.emissive,
        opacity = output.opacity,
        material_channel = output.material_channel,
    )
}

pub(crate) fn material_scene_table_product_wgsl(slots: &[SceneMaterialTableProgramSlot<'_>]) -> String {
    let first = slots
        .first()
        .expect("scene material table compiler validates non-empty slots");
    let base = material_scene_product_wgsl(first.ir, &first.program);
    let Some(evaluate_start) = base.find("fn evaluate_material(ctx: MaterialEvalContext)") else {
        return base;
    };
    let Some(scene_tail_start) = base.find("fn sdf_box(") else {
        return base;
    };
    let mut evaluators = String::new();
    for slot in slots {
        evaluators.push_str(&format!(
            "// scene material slot {} instance {}\n",
            slot.slot_index, slot.material_instance_id
        ));
        evaluators.push_str(&slot_evaluator_wgsl(slot));
        evaluators.push('\n');
    }
    evaluators.push_str(
        r#"const MATERIAL_TABLE_SLOT_CAPACITY : u32 = 64u;

fn material_error_output(material_slot_index: u32) -> MaterialEvalOutput {
    var out: MaterialEvalOutput;
    out.base_color = vec4<f32>(1.0, 0.0, 0.85, 1.0);
    out.roughness = 1.0;
    out.metallic = 0.0;
    out.normal_strength = 1.0;
    out.emissive = vec3<f32>(0.35, 0.0, 0.25);
    out.opacity = 1.0;
    out.material_channel = f32(material_slot_index);
    return out;
}

fn evaluate_scene_material(material_slot_index: u32, ctx: MaterialEvalContext) -> MaterialEvalOutput {
    switch material_slot_index {
"#,
    );
    for slot in slots {
        evaluators.push_str(&format!(
            "        case {}u: {{ return evaluate_material_slot_{}(ctx); }}\n",
            slot.slot_index, slot.slot_index
        ));
    }
    evaluators.push_str(
        r#"        default: { return material_error_output(material_slot_index); }
    }
}

"#,
    );
    format!(
        "{}{}{}",
        &base[..evaluate_start],
        evaluators,
        &base[scene_tail_start..]
    )
}

fn slot_evaluator_wgsl(slot: &SceneMaterialTableProgramSlot<'_>) -> String {
    let generated_lines = if slot.program.lines.is_empty() {
        String::new()
    } else {
        let mut lines = slot.program.lines.join("\n");
        lines.push('\n');
        lines
    };
    let output = &slot.program.output;
    format!(
        r#"fn evaluate_material_slot_{slot_index}(ctx: MaterialEvalContext) -> MaterialEvalOutput {{
{generated_lines}    var out: MaterialEvalOutput;
    out.base_color = {base_color};
    out.roughness = clamp({roughness}, 0.0, 1.0);
    out.metallic = clamp({metallic}, 0.0, 1.0);
    out.normal_strength = max({normal_strength}, 0.0);
    out.emissive = {emissive};
    out.opacity = clamp({opacity}, 0.0, 1.0);
    out.material_channel = {material_channel};
    return out;
}}
"#,
        slot_index = slot.slot_index,
        base_color = output.base_color,
        roughness = output.roughness,
        metallic = output.metallic,
        normal_strength = output.normal_strength,
        emissive = output.emissive,
        opacity = output.opacity,
        material_channel = output.material_channel,
    )
}
