[package]
name = "runenwerk_render_lab"
version = "0.1.0"
edition = "2024"
publish = false
license.workspace = true

[dependencies]
anyhow = "1.0.100"
blake3 = "1.8.2"
engine = { path = "../../engine" }
image = { version = "0.25.8", default-features = false, features = ["png"] }
pollster = "0.4.0"
runen-gpu.workspace = true
runen_ecs.workspace = true
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.145"
winit = "0.30.9"

[[bin]]
name = "runenwerk-render-lab"
path = "src/main.rs"
